# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MogileFS-Client-FilePaths
version:      0.01
version_from: lib/MogileFS/Client/FilePaths.pm
installdirs:  site
requires:
    MogileFS::Client:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
